/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGooBalanceProxy } from "./IGooBalanceProxy";
export type { IGooTogether } from "./IGooTogether";
export type { GooPoints } from "./GooPoints";
