/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface GooBalanceProxyInterface extends utils.Interface {
  functions: {
    "balanceOf(address)": FunctionFragment;
    "gobblers()": FunctionFragment;
    "gooToken()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "balanceOf"
      | "balanceOf(address)"
      | "gobblers"
      | "gobblers()"
      | "gooToken"
      | "gooToken()"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "gobblers", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gobblers()",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gooToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gooToken()",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOf(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gobblers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gobblers()", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gooToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gooToken()", data: BytesLike): Result;

  events: {};
}

export interface GooBalanceProxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GooBalanceProxyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    balanceOf(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "balanceOf(address)"(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    gobblers(overrides?: CallOverrides): Promise<[string]>;

    "gobblers()"(overrides?: CallOverrides): Promise<[string]>;

    gooToken(overrides?: CallOverrides): Promise<[string]>;

    "gooToken()"(overrides?: CallOverrides): Promise<[string]>;
  };

  balanceOf(
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "balanceOf(address)"(
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  gobblers(overrides?: CallOverrides): Promise<string>;

  "gobblers()"(overrides?: CallOverrides): Promise<string>;

  gooToken(overrides?: CallOverrides): Promise<string>;

  "gooToken()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    balanceOf(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "balanceOf(address)"(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gobblers(overrides?: CallOverrides): Promise<string>;

    "gobblers()"(overrides?: CallOverrides): Promise<string>;

    gooToken(overrides?: CallOverrides): Promise<string>;

    "gooToken()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    balanceOf(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "balanceOf(address)"(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gobblers(overrides?: CallOverrides): Promise<BigNumber>;

    "gobblers()"(overrides?: CallOverrides): Promise<BigNumber>;

    gooToken(overrides?: CallOverrides): Promise<BigNumber>;

    "gooToken()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    balanceOf(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address)"(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gobblers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "gobblers()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gooToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "gooToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
