/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGobblers } from "./IGobblers";
export type { IGooPoints } from "./IGooPoints";
export type { GooTogether } from "./GooTogether";
