/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGooTogether,
  IGooTogetherInterface,
} from "../../gooPoints.sol/IGooTogether";

const _abi = [
  {
    inputs: [],
    name: "calculateInterest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "gooPoints",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IGooTogether__factory {
  static readonly abi = _abi;
  static createInterface(): IGooTogetherInterface {
    return new utils.Interface(_abi) as IGooTogetherInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGooTogether {
    return new Contract(address, _abi, signerOrProvider) as IGooTogether;
  }
}
