/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGooBalanceProxy__factory } from "./IGooBalanceProxy__factory";
export { IGooTogether__factory } from "./IGooTogether__factory";
export { GooPoints__factory } from "./GooPoints__factory";
