/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGobblers,
  IGobblersInterface,
} from "../../gooBalanceProxy.sol/IGobblers";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "gooBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IGobblers__factory {
  static readonly abi = _abi;
  static createInterface(): IGobblersInterface {
    return new utils.Interface(_abi) as IGobblersInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGobblers {
    return new Contract(address, _abi, signerOrProvider) as IGobblers;
  }
}
