/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGobblers__factory } from "./IGobblers__factory";
export { GooBalanceProxy__factory } from "./GooBalanceProxy__factory";
